membership/urls.py
from django.urls import path
from membership import views

app_name = "membership"

urlpatterns = [
    path('<int:user_n>/information/', views.information, name="information"),
    path("<int:user_n>/information/recharge/", views.recharge, name="recharge"),
    path('<int:user_n>/information/history/', views.history, name="history"),
    path('<int:history_id>/information/history/create/', views.r_create, name="create"),
]

order/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView
from order import views

app_name = 'order'


urlpatterns = [
    #김은수
    path('menu', views.menu, name='menu'),
    path('<int:product_cd>/detail', views.detail, name='detail'),
    path('cart', views.cart, name='cart'),
    path('<int:cart_id>/delete',views.cart_delete, name='c_delete'),
    path('address', views.address, name='address'),
    path('insert_adr', views.insert_adr, name='insert_adr')

    #김은수
]

starbucks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView
from starbucks import views

urlpatterns = [

    path('accounts/', include('accounts.urls')),  # 아인
    url(r"^$",  views.give_reviews, name="home"),  # 근웅
    # url(r"^$", TemplateView.as_view(template_name="index.html"), views.give_reviews,name="home"),
    path('admin/', admin.site.urls),
    path("membership/", include("membership.urls")),
    path('order/', include('order.urls'))
]

membership/models.py
from django.db import models
from accounts.models import User
from django import forms

def min_length_10_validator(value):
    if len(value) < 10 :
        raise forms.ValidationError('최소 10자 이상 입력해주세요.')

class Gift_card(models.Model):
    name = models.CharField(max_length=10)
    value = models.IntegerField()
    serial_number = models.IntegerField()

    def __str__(self):
        return self.name

class History(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField('상품명',max_length=20,null=True)
    quantity = models.IntegerField('수량',default=0)
    total = models.IntegerField('총가격',default=0)
    order_date = models.DateField(auto_now=True)
    cd = models.IntegerField('cd',null=True)
    category = models.CharField('카테고리',max_length=20,null=True)
    completed = models.BooleanField('후기유무',default=False)
    select_adr = models.CharField('주문매장', max_length=20, blank=True, null=True)
    order_no = models.IntegerField('주문번호',default=0)


    def __str__(self):
        return self.name

class Review(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    history = models.ForeignKey(History, on_delete=models.CASCADE)
    create_date = models.DateField(auto_now=True)
    comment = models.TextField("글내용",max_length=1000, validators=[min_length_10_validator])

    def __str__(self):
        return self.comment

membership/forms.py
from django import forms
from membership.models import Review


class ReviewForm(forms.ModelForm):
    class Meta :
        model = Review
        fields =['comment']
        widgets = {
            'comment': forms.Textarea(attrs={'placeholder': '상품 만족도에 대한 후기를 남겨주세요.(최소 10자 이상 입력해주세요.)',
                                             'class':'form-control',
                                             'name' : 'review',
                                             'cols' : '30',
                                             'rows' : '7' }),
        }

membership/views.py
from django.shortcuts import render, get_object_or_404, redirect
from membership.models import Gift_card, History, Review
from accounts.models import User
from django.contrib import messages
from membership.forms import ReviewForm
from django.http import HttpResponse

def information(request,user_n) :
    user = get_object_or_404(User, id=user_n)
    context ={"user" : user}
    return render(request,"information.html",context)

def recharge(request, user_n) :
    user = get_object_or_404(User, id=user_n)
    giftcard_list = Gift_card.objects.all()
    serial_list = [giftcard.serial_number for giftcard in giftcard_list]

    if request.POST["serial"].isdecimal():
        get_number =  int( request.POST["serial"] )
        if get_number in serial_list:
            for k in range(0,len(giftcard_list)):
                n = serial_list[k]
                if n == get_number:
                    user.point += giftcard_list[k].value
                    user.save()
                    break
            return redirect("membership:information", user_n)
        else:
            messages.add_message(request, messages.INFO, '존재하지 않는 번호입니다.')
            return redirect("membership:information", user_n)

    else:
        messages.add_message(request, messages.INFO, '잘못된 입력입니다.')
        return redirect("membership:information", user_n)

def history(request) :
    if request.method == "POST":
        return render(request, "history.html")

    else :
        return render(request, "history.html",{"history":[]})


# -------------------근웅------------------
def history(request, user_n):
    user = get_object_or_404(User, id=user_n)
    user_histories = user.history_set.all().order_by('-id')
    return render(request, "history.html",{"histories": user_histories, 'user' : user}) #김은수 : context에 user 추가


# def r_create(request, history_id):
#     if request.method == "POST":
#         user_n = request.session["user_n"]
#         history = get_object_or_404(History, id = history_id)
#         comment = request.POST["review"]
#         if True:   # 나중에 최소글자수 추가 할수도 있음
#             Review.objects.create(user_id = user_n, history_id = history.id, comment = comment)
#             return redirect("membership:history", user_n)
#     else:
#         return render(request,"create.html")
# ---------------------------------------
def r_create(request, history_id):
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)                # comment
            review.user_id = request.session['user_n']      # user
            history = get_object_or_404(History, id = history_id)
            history.completed = True
            history.save()
            review.history_id = history.id                  # history
            review.save()
            # ----------reviews of index---------
            # reviews = Review.objects.all().order_by('-id')
            # j = 1
            # for recent in reviews :
            #     if j == 6:
            #         break
            #     user = get_object_or_404(User,id=recent.user_id)
            #     product = get_object_or_404(History,id=recent.history_id)
            #     request.session['recent{}_user'.format(j)]  = user.user_id
            #     request.session['recent{}_comment'.format(j)] =  recent.comment
            #     request.session['recent{}_product'.format(j)] =  product.name
            #     request.session['recent{}_date'.format(j)] = product.order_date.strftime('%Y-%m-%d')
            #     request.session['recent{}_cd'.format(j)] = product.cd
            #     request.session['recent{}_category'.format(j)] = product.category
            #     j+=1
            #------------------------------------
            return redirect('membership:history', request.session['user_n'] )
    else:
        form = ReviewForm()
    return render(request, 'create.html' ,{'form':form})
# # ---------------------------------------

membership/templates/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Coffee - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">

    <link rel="stylesheet" href="/static/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/animate.css">
    
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/static/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="/static/css/magnific-popup.css">

    <link rel="stylesheet" href="/static/css/aos.css">

    <link rel="stylesheet" href="/static/css/ionicons.min.css">

    <link rel="stylesheet" href="/static/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="/static/css/jquery.timepicker.css">


      <link rel="stylesheet" href="/static/css/flaticon.css">
      <link rel="stylesheet" href="/static/css/icomoon.css">
      <link rel="stylesheet" href="/static/css/style.css">


  </head>
  <body>

  {% include "navbar.html"  %}
    <!-- END nav -->

    <section class="home-slider owl-carousel">

      <div class="slider-item" style="background-image: url(/static/images/bg_3.jpg);" data-stellar-background-ratio="0.5">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center">

            <div class="col-md-7 col-sm-12 text-center ftco-animate">
            	<h1 class="mb-3 mt-5 bread">리뷰 작성하기</h1>
<!--	            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Order History</span></p>-->
            </div>

          </div>
        </div>
      </div>
    </section>

    <section class="ftco-section contact-section">
        <div class="container mt-5">
            <h2 class="h2">상품은 마음에 드셨나요?</h2>
            <div class="row block-9">
                <div class="col-md-6 ftco-animate">
                    <form method="post" class="contact-form">
                          {% csrf_token %}
                        <div class="form-group">
                            {% for field in form.visible_fields %}
                            <tr>
                                <td>
                                    {{ field }}
                                    {% for error  in field.errors %}
                                    <div>
                                        <p class="text-danger">
                                            {{error}}
                                        </p>
                                    </div>
                                    {% endfor %}
                                </td>
                            </tr>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <input type="submit" value="작성 완료" class="btn btn-primary py-3 px-5">

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!------------------------------------------------------------------->

  {% include "footer.html" %}

  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="/static/js/jquery.min.js"></script>
  <script src="/static/js/jquery-migrate-3.0.1.min.js"></script>
  <script src="/static/js/popper.min.js"></script>
  <script src="/static/js/bootstrap.min.js"></script>
  <script src="/static/js/jquery.easing.1.3.js"></script>
  <script src="/static/js/jquery.waypoints.min.js"></script>
  <script src="/static/js/jquery.stellar.min.js"></script>
  <script src="/static/js/owl.carousel.min.js"></script>
  <script src="/static/js/jquery.magnific-popup.min.js"></script>
  <script src="/static/js/aos.js"></script>
  <script src="/static/js/jquery.animateNumber.min.js"></script>
  <script src="/static/js/bootstrap-datepicker.js"></script>
  <script src="/static/js/jquery.timepicker.min.js"></script>
  <script src="/static/js/scrollax.min.js"></script>
  <script src="/static/js/main.js"></script>
    
  </body>
</html>

membership/templates/history.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Coffee - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">

 <link rel="stylesheet" href="/static/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/animate.css">
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/static/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="/static/css/magnific-popup.css">
    <link rel="stylesheet" href="/static/css/aos.css">
    <link rel="stylesheet" href="/static/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="/static/css/jquery.timepicker.css">
    <link rel="stylesheet" href="/static/css/flaticon.css">
    <link rel="stylesheet" href="/static/css/icomoon.css">
    <link rel="stylesheet" href="/static/css/style.css">
  </head>
<!------------------------------------------------------------------------------------------------>
  <body>

  {% include "navbar.html"  %}
    <!-- END nav -->


      <section class="home-slider owl-carousel">
      <div class="slider-item" style="background-image: url(/static/images/bg_3.JPG);" data-stellar-background-ratio="0.5">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center">
            <div class="col-md-7 col-sm-12 text-center ftco-animate">
            	<h1 class="mb-3 mt-5 bread">My Starbucks</h1>
	            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'membership:information' user.id %}" class="py-2 d-block">My profile</a></span>
                    <span>
                        Order History
                    </span>
                </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  

		<section class="ftco-section ftco-cart">
			<div class="container">
				<div class="row">
<!--                    <label> {{user.select_adr}} </label>-->
					<div class="col-md-12 ftco-animate">
                        <div class="cart-list">
                            <table class="table">
                                <thead class="thead-primary">
                                <tr class="text-center">
                                    <th>주문번호</th>
                                    <th>제품</th>
                                    <th>제품명</th>
                                    <th>개수</th>
                                    <th>주문금액</th>
                                    <th>주문일자</th>
                                    <th>주문매장</th>
                                    <th>후기</th>
                                </tr>
                                <tbody>
                                {%for history in histories%}
                                <tr class="text-center">
                                    <td class="total">{{history.order_no}}</td>
                                    <td class="image-prod"><div class="img" style="background-image:url(/static/images/{{history.category}}/{{history.cd}}.jpg);"></div></td>
                                    <td class="product-name">
                                        <a href="/order/{{history.cd}}/detail?kind={{history.category}}">{{history.name}}</a>
                                    </td>
                                    <td class="total">{{history.quantity}}</td>
                                    <td class="total">{{history.total}}</td>
                                    <td class="total">{{history.order_date|date:"Y-m-d"}}</td>
                                    <td class="total">{{history.select_adr}}</td>
                                    {%if history.review_set.all%}
                                            <td class="total">작성완료</td>
                                    {%else%}
                                            <td class="total"><a class="btn btn-primary btn-outline-primary"  href="{% url 'membership:create' history.id%}">작성하기</a></td>
                                    {%endif%}
                                </tr>
                                {%endfor%}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
			</div>
		</section>


  {% include "footer.html" %}




  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="/static/js/jquery.min.js"></script>
  <script src="/static/js/jquery-migrate-3.0.1.min.js"></script>
  <script src="/static/js/popper.min.js"></script>
  <script src="/static/js/bootstrap.min.js"></script>
  <script src="/static/js/jquery.easing.1.3.js"></script>
  <script src="/static/js/jquery.waypoints.min.js"></script>
  <script src="/static/js/jquery.stellar.min.js"></script>
  <script src="/static/js/owl.carousel.min.js"></script>
  <script src="/static/js/jquery.magnific-popup.min.js"></script>
  <script src="/static/js/aos.js"></script>
  <script src="/static/js/jquery.animateNumber.min.js"></script>
  <script src="/static/js/bootstrap-datepicker.js"></script>
  <script src="/static/js/jquery.timepicker.min.js"></script>
  <script src="/static/js/scrollax.min.js"></script>
<!--  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>-->
  <script src="/static/js/google-map.js"></script>
  <script src="/static/js/main.js"></script>


  </body>
</html>

membership/templates/information.html
<!DOCTYPE html>
<html lang="en">
  <head>

    <title>Coffee - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/animate.css">

    <link rel="stylesheet" href="/static/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/static/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="/static/css/magnific-popup.css">

    <link rel="stylesheet" href="/static/css/aos.css">

    <link rel="stylesheet" href="/static/css/ionicons.min.css">

    <link rel="stylesheet" href="/static/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="/static/css/jquery.timepicker.css">


    <link rel="stylesheet" href="/static/css/flaticon.css">
    <link rel="stylesheet" href="/static/css/icomoon.css">
    <link rel="stylesheet" href="/static/css/style.css">
  </head>
<!--------------------------------------------------------------------------------->
  <body>

  {% include "navbar.html"  %}
    <!-- END nav -->

    <section class="home-slider owl-carousel">
      <div class="slider-item" style="background-image: url(/static/images/bg_3.JPG);" data-stellar-background-ratio="0.5">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center">
            <div class="col-md-7 col-sm-12 text-center ftco-animate">
            	<h1 class="mb-3 mt-5 bread">My Starbucks</h1>
	            <p class="breadcrumbs"><span class="mr-2">My profile</span>
                    <span>
                        <a href="{% url 'membership:history' user.id %}" class="py-2 d-block">Order History</a>
                    </span>
                </p>
            </div>
          </div>
        </div>
      </div>
    </section>



    <section class="ftco-section contact-section" id="section1">
        <div class="container mt-5">
            <div class="row block-9">
                <div class="col-md-4 contact-info ftco-animate">
                    <div class="row">
                        <div class="col-md-12 mb-4">
                            <h2 class="h4">{{user.user_name}}님 환영합니다.</h2>
                        </div>
                        <div class="col-md-12 mb-3">
                            <span class="text-white">내 아이디 :&nbsp &nbsp</span> <span>{{user.user_id}}</span>
                        </div>
                        <div class="col-md-12 mb-3">
                            <span class="text-white">내 전화번호 :&nbsp &nbsp</span> <span>{{user.phone_num}}</span>
                        </div>
                        <div class="col-md-12 mb-3">
                            <span class="text-white">내 마일리지 :&nbsp &nbsp</span>  <span>{{user.point}} point</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-1"></div>

                <div class="col-md-6 ftco-animate">
                    <form action="{% url 'membership:recharge' user.id %}" class="contact-form" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <br><br>
                                    <input type="text" class="form-control" placeholder="상품권 일련번호" name="serial">
                                    {% if messages %}
                                    <div>
                                        <p class="text-danger">
                                        {% for message in messages %}
                                        {{ message.message }}
                                        </p>
                                    </div>
                                    {% endfor %}
                                    {% else %}
                                    <div>
                                        "-"를 제외한 숫자입력
                                    </div>
                                    {% endif %}

                                </div>
                                <input type="submit" value="마일리지 충전하기" class="btn btn-primary py-3 px-5">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

  {% include "footer.html" %}



  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="/static/js/jquery.min.js"></script>
  <script src="/static/js/jquery-migrate-3.0.1.min.js"></script>
  <script src="/static/js/popper.min.js"></script>
  <script src="/static/js/bootstrap.min.js"></script>
  <script src="/static/js/jquery.easing.1.3.js"></script>
  <script src="/static/js/jquery.waypoints.min.js"></script>
  <script src="/static/js/jquery.stellar.min.js"></script>
  <script src="/static/js/owl.carousel.min.js"></script>
  <script src="/static/js/jquery.magnific-popup.min.js"></script>
  <script src="/static/js/aos.js"></script>
  <script src="/static/js/jquery.animateNumber.min.js"></script>
  <script src="/static/js/bootstrap-datepicker.js"></script>
  <script src="/static/js/jquery.timepicker.min.js"></script>
  <script src="/static/js/scrollax.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="/static/js/google-map.js"></script>
  <script src="/static/js/main.js"></script>

  </body>
</html>