order/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView
from order import views

app_name = 'order'


urlpatterns = [
    #김은수
    path('menu', views.menu, name='menu'),
    path('<int:product_cd>/detail', views.detail, name='detail'),
    path('cart', views.cart, name='cart'),
    path('<int:cart_id>/delete',views.cart_delete, name='c_delete'),
    path('address', views.address, name='address'),
    path('insert_adr', views.insert_adr, name='insert_adr')

    #김은수
]

starbucks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView
from starbucks import views

urlpatterns = [

    path('accounts/', include('accounts.urls')),  # 아인
    url(r"^$",  views.give_reviews, name="home"),  # 근웅
    # url(r"^$", TemplateView.as_view(template_name="index.html"), views.give_reviews,name="home"),
    path('admin/', admin.site.urls),
    path("membership/", include("membership.urls")),
    path('order/', include('order.urls'))
]

order/models.py
from django.db import models
from accounts.models import User


# coffee,desserts,goods 모델 추가 김은수
class Coffee(models.Model):
    text = models.CharField(max_length=100)
    cd = models.IntegerField()
    name = models.CharField(max_length=40)
    allergy = models.CharField(max_length=100, blank=True, null=True)
    kcal = models.IntegerField()
    sat_fat = models.IntegerField(db_column='sat_FAT')  # Field name made lowercase.
    protein = models.IntegerField()
    fat = models.IntegerField()
    trans_fat = models.IntegerField(db_column='trans_FAT')  # Field name made lowercase.
    sodium = models.IntegerField()
    sugars = models.IntegerField()
    cholesterol = models.IntegerField()
    chabo = models.IntegerField()
    price = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'Coffee'

    def __str__(self):
        return self.name


class Desserts(models.Model):
    text = models.CharField(max_length=100)
    cd = models.IntegerField()
    name = models.CharField(max_length=40)
    gram = models.IntegerField()
    allergy = models.CharField(max_length=100, blank=True, null=True)
    price = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'Desserts'

    def __str__(self):
        return self.name


class Goods(models.Model):
    text = models.CharField(max_length=100)
    cd = models.IntegerField()
    name = models.CharField(max_length=40)
    price = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'Goods'

    def __str__(self):
        return self.name


class Carts(models.Model):
    identity = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField('상품명', max_length=40, null=True)
    price = models.IntegerField('가격', default=0)
    quantity = models.IntegerField('수량', default=0)
    total = models.IntegerField('총가격', default=0)
    cd = models.IntegerField('cd', null=True)
    category = models.CharField('카테고리', max_length=20, null=True)

    def __str__(self):
        return self.name


class StarbucksAddress(models.Model):
    name = models.CharField(max_length=40)
    address = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'starbucks_address'

order/views.py
from django.shortcuts import render, redirect, get_object_or_404
from order.models import Coffee, Desserts, Goods, Carts, StarbucksAddress
from accounts.models import User
from membership.models import History, Review
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
import math
import random
from datetime import datetime


# Create your views here.

# menu 함수 작성 김은수
def menu(request):
    if request.method == "POST":
        redirect("menu.html")
    else:
        coffee = Coffee.objects.all()
        desserts = Desserts.objects.all()
        goods = Goods.objects.all()

        context = {"coffee": coffee, "desserts": desserts, "goods": goods
                   }
        return render(request, 'menu.html', context)


# 상세보기 함수 김은수
def detail(request, product_cd):
    if request.method == "POST":
        if not request.session["check"] == 1:
            return HttpResponse('<script type="text/javascript">alert("로그인이필요합니다.");history.back(); '
                                '</script>')

        category = request.GET['kind']
        user_id = request.session['user_id']

        quantity = int(request.POST["quantity"])
        session = get_object_or_404(User, user_id=user_id)

        if category == "coffee":
            product = get_object_or_404(Coffee, cd=product_cd)
           
        elif category == "desserts":
            product = get_object_or_404(Desserts, cd=product_cd)
        else:
            product = get_object_or_404(Goods, cd=product_cd)

        cart = Carts(identity=session)

        all_cart = Carts.objects.filter(identity=session)

        if all_cart.exists():
            count = 0
            for i in all_cart:
                if i.cd == product_cd:
                    i.quantity += quantity
                    i.total = i.price * i.quantity
                    i.save()
                    count = 1
                    break

            if count == 0:
                cart.name = product.name
                cart.price = product.price
                cart.quantity = quantity
                cart.total = product.price * quantity
                cart.cd = product_cd
                cart.category = category

                cart.save()

        else:
            cart.name = product.name
            cart.price = product.price
            cart.quantity = quantity
            cart.total = product.price * quantity
            cart.cd = product_cd
            cart.category = category

            cart.save()

        flag = request.POST["flag"]

        if flag == "true":
            return redirect("order:cart")
        else:
            return redirect("order:menu")
    else:

        if request.GET['kind'] == 'desserts':

            product = get_object_or_404(Desserts, cd=product_cd)

            product_list = Desserts.objects.all()

            category = "desserts"

        elif request.GET['kind'] == 'coffee':

            product = get_object_or_404(Coffee, cd=product_cd)

            product_list = Coffee.objects.all()

            category = "coffee"
        else:

            product = get_object_or_404(Goods, cd=product_cd)

            product_list = Goods.objects.all()

            category = "goods"

        # ------------ 근웅 ------------
        histories = History.objects.filter(completed=True)
        reviews = []
        for history in histories:
            if history.cd == product_cd and history.category == category:
                reviews.append(get_object_or_404(Review, history_id=history.id))
        # -----------------------------

        count = 0
        random_list = []
        while count < 4:
            for i in product_list:
                ran = random.randrange(0, 30)
                if i.id == ran:
                    random_list.append(i)
                    count += 1
                    if count == 4:
                        break
        print(random_list)
        context = {"list": product, "category": category, "reviews": reviews, "product_list": product_list,
                   "random_list": random_list}
        return render(request, 'menu_detail.html', context)


# 장바구니 함수 김은수
def cart(request):
    user_id = request.session['user_id']
    user = get_object_or_404(User, user_id=user_id)
    my_cart = Carts.objects.filter(identity=user)

    print(user)
    pay_products = 0

    for i in my_cart:
        pay_products = pay_products + i.total

    if request.method == "POST":

        if user.select_adr == None:
            return HttpResponse(
                '<script type="text/javascript">alert("take out하실 매장을 선택해주세요.");history.back();</script>')
        elif not my_cart.exists():
            return HttpResponse('<script type="text/javascript">alert("결제할 메뉴가없습니다.");history.back();</script>')

        pay = request.POST["flag"]

        if pay == "true":
            # ----------박근웅----------
            order_no = int(datetime.today().strftime('%Y%m%d%H%M'))

            for i in my_cart:
                History.objects.create(user_id=user.id, name=i.name, quantity=i.quantity, total=i.total, cd=i.cd,
                                       category=i.category, order_no=order_no, select_adr=user.select_adr)
            # -------------------------
            user.point = user.point - pay_products
            if user.point >= 0:
                user.save()
                my_cart.delete()
                return redirect("/membership/{}/information/history".format(user.id))
            else:
                return HttpResponse('<script type="text/javascript">alert("충전금액이 모자릅니다");history.back();</script>')
        else:
            return redirect("order:cart")


    else:

        total = user.point - pay_products

        context = {"carts": my_cart, "total": total, "pay_products": pay_products, "user": user}

        return render(request, 'cart.html', context)


def cart_delete(reqeust, cart_id):
    cart = get_object_or_404(Carts, id=cart_id)
    cart.delete()
    return redirect('order:cart')


def address(request):
    if request.method == "POST":
        flag = False
        address_list = StarbucksAddress.objects.all()

        search_adr = request.POST.get("input_search")

        result_list = []

        for i in address_list:
            if search_adr in i.address:
                search = StarbucksAddress()
                search.name = i.name
                search.address = i.address
                result_list.append(search)

        context = {"flag": flag, "adr_list": result_list}
        return render(request, 'address.html', context)

    else:
        flag = True
        context = {"flag": flag}
        return render(request, 'address.html', context)


def insert_adr(request):
    user_id = request.session['user_id']

    session = get_object_or_404(User, user_id=user_id)

    adrValue = request.GET.get('adrValue')

    session.select_adr = adrValue

    print(session.select_adr)

    session.save()

    return HttpResponse('<script type="text/javascript">window.close();opener.location.reload();</script>')

# def paging(request, list):
#     paginator = Paginator(list, 3)
#     page = request.GET.get('page')
#     contacts = paginator.get_page(page)
#
#     return contacts

order/templates/address.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="/static/css/css/addressSearch.css" />
        <link rel="stylesheet" href="/static/css/css/address.css" />
        <link
            href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap"
            rel="stylesheet"
        />
        <title>Coffee | address</title>
    </head>
    <body>

                {% if flag %}
        <div class="address_search">
                    <form name="search_adr" method="post">
                                    {% csrf_token %}
            <div class="address_search-bar">

                <div class="address_search-input">
                    <input
                        class="search-input"
                        type="text"
                        placeholder="여기에 주소를 입력하세요"
                        name = "input_search"
                    />

                </div>
                <div class="adderss_search-icon">
                    <input
                        class="search-icon"
                        type="image"
                        src="https://img.icons8.com/fluent-systems-regular/24/000000/search.png"/>

                </div>
            </div>
                         </form>

            <div class="address_search-tip">
                <strong>tip</strong>
                <p class="search_p">
                    지역 구 <br />
                    <span class="example"> 예) 강남구</span>
                </p>
                <p class="search_p">
                    지역명(동/리) <br />
                    <span class="example">
                        삼성동</span
                    >
                </p>
                <p class="search_p">
                    지역구 + 도로명 <br />
                    <span class="example"> 예) 강남구 테헤란로</span>
                </p>
                 </div>

        </div>
                {% else %}
        <div class="address_search">
            <form name="search_adr" method="post">
                                    {% csrf_token %}
            <div class="address_search-bar">
                <div class="address_search-input">
                    <input
                        class="search-input"
                        type="text"
                        name="input_search"
                        placeholder="예) 판교역로"
                    />
                </div>
                <div class="adderss_search-icon">
                    <input
                        class="search-icon"
                        type="image"
                        src="https://img.icons8.com/fluent-systems-regular/24/000000/search.png"
                    />
                </div>
            </div>
            </form>
            <div class="address_search-tip">
                <strong>아래와 같이 검색해 보세요.</strong>
                <p>
                    <span>'도로명',</span>
                    <span>'지역명',</span>
                    <span>'지역구',</span>
                </p>
            </div>

                        {% if adr_list %}
            <div class="address_search-list">
                <ul>
                        {% for adr in adr_list %}

                    <li>
                        <form name="insert_adr" method="get" action="{% url 'order:insert_adr' %}">
                                    {% csrf_token %}
                        <div class="list-head">
                            <div class="post">
                                <button class="post" onclick="submit_adr()">선택</button>
                                </div>
                            <input type="hidden" name="adrValue" value="{{ adr.name }}">
                            <div class="option">
                                <div class="option_en">영문보기</div>
                                <div class="option_map">지도</div>
                            </div>
                        </div>

                            <div class="list-location">
                                <div class="location_title">도로명</div>
                                <div>
                                    <div> {{ adr.address }}</div>
                                    </div>
                            </div>
                            <div class="list-location">
                                <div class="location_title">매장명</div>
                                <div>
                                    {{ adr.name }}</div>
                            </div>
                            </form>
                    </li>

                        {% endfor %}

                    <!--  더미데이터 실제 작업시엔 윗줄만 사용하면 됩니다. -->

                </ul>
            </div>

                    {% endif %}
        </div>
                {% endif %}

    </body>
<script>
    function submit_adr(){
        document.insert_adr.action = "${pageContext.request.contextPath}";
        document.insert_adr.submit();
        window.open('about:blank','_self').close();
    }
</script>
</html>

order/templates/cart.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Coffee - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">

    <link rel="stylesheet" href="/static/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/animate.css">
    
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/static/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="/static/css/magnific-popup.css">

    <link rel="stylesheet" href="/static/css/aos.css">

    <link rel="stylesheet" href="/static/css/ionicons.min.css">

    <link rel="stylesheet" href="/static/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="/static/css/jquery.timepicker.css">

    
    <link rel="stylesheet" href="/static/css/flaticon.css">
    <link rel="stylesheet" href="/static/css/icomoon.css">
    <link rel="stylesheet" href="/static/css/style.css">
	  <style>
          body .test{
                        display:flex;
                        margin-bottom:0.5rem;
                        }
          body .center{
                        width:50%;
                        display:flex;
                        flex-direction:column;
                        justify-content:center;
                        }
          body .btn_color{
                        color:black !important;
                        }
          body .btn_color:hover{
                        color:#c49b63 !important;
                        }
      </style>
  </head>
  <body>

  {% include "navbar.html"  %}
    <!-- END nav -->

    <section class="home-slider owl-carousel">

      <div class="slider-item" style="background-image: url(/static/images/bg_2.jpg);" data-stellar-background-ratio="0.5">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center">

            <div class="col-md-7 col-sm-12 text-center ftco-animate">
            	<h1 class="mb-3 mt-5 bread">Cart</h1>
	            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Cart</span></p>
            </div>

          </div>
        </div>
      </div>
    </section>
		
		<section class="ftco-section ftco-cart">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">
    				<div class="cart-list">
	    				<table class="table">
						    <thead class="thead-primary">
						      <tr class="text-center">
						        <th>&nbsp;</th>
						        <th>&nbsp;</th>
						        <th>Product</th>
						        <th>Price</th>
						        <th>Quantity</th>
						        <th>Total</th>
						      </tr>
						    </thead>
						    <tbody>
								  {% for cart in carts %}
						      <tr class="text-center">
						        <td class="product-remove"><a href="{% url 'order:c_delete' cart.id %}"><span class="icon-close"></span></a></td>
						        
						        <td class="image-prod"><div class="img" style="background-image:url(/static/images/{{cart.category}}/{{cart.cd}}.jpg);"></div></td>
						        
						        <td class="product-name">
						        	<h3>{{cart.name}}</h3>
						        	<p>
										<a href="/order/{{ cart.cd }}/detail?kind={{ cart.category }}">상세보기</a>
									</p>
						        </td>
						        
						        <td class="price">${{cart.price}}</td>

						        <td class="quantity"> {{cart.quantity}}</td>
						        
						        <td class="total">${{cart.total}}</td>
						      </tr><!-- END TR-->
								  {% endfor %}

						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
				<div class="row justify-content-end">

    			<div class="col col-lg-3 col-md-6 mt-5 cart-wrap ftco-animate">
    				<div class="cart-total mb-3">
						<p class="d-flex">
							<span> {{ user.select_adr }} </span>
						</p>
						<p class="text-center"><button type="button" class="btn_color btn btn-primary py-3 px-4" onclick="window.open('{% url 'order:address' %}','window팝업','width=470,height=600,top=100,left=500');">매장 검색</button></p>

					</div>
				</div>
				</div>
    		<div class="row justify-content-end">
    			<div class="col col-lg-3 col-md-6 mt-5 cart-wrap ftco-animate">
    				<div class="cart-total mb-3">

    					<h3>Cart Totals</h3>
    					<p class="d-flex">
    						<span>My_Point</span>
    						<span>${{ user.point }}</span>
    					</p>
    					<p class="d-flex">
    						<span>Payment</span>
    						<span>${{ pay_products }}</span>
    					</p>
    					<hr>
    					<p class="d-flex total-price">
    						<span>Remaining</span>
    						<span>{{ total }}</span>
    					</p>
    				</div>
					<form name="form_pay" method="post">
                                    {% csrf_token %}
    				<p class="text-center"><button type="button" class="btn_color btn btn-primary py-3 px-4" onclick="payment()">Proceed to Checkout</button></p>

					<input type="text" id="flag" name="flag" value="true" hidden="true">
						</form>
    			</div>
    		</div>
			</div>
		</section>

  {% include "footer.html" %}

    
  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="/static/js/jquery.min.js"></script>
  <script src="/static/js/jquery-migrate-3.0.1.min.js"></script>
  <script src="/static/js/popper.min.js"></script>
  <script src="/static/js/bootstrap.min.js"></script>
  <script src="/static/js/jquery.easing.1.3.js"></script>
  <script src="/static/js/jquery.waypoints.min.js"></script>
  <script src="/static/js/jquery.stellar.min.js"></script>
  <script src="/static/js/owl.carousel.min.js"></script>
  <script src="/static/js/jquery.magnific-popup.min.js"></script>
  <script src="/static/js/aos.js"></script>
  <script src="/static/js/jquery.animateNumber.min.js"></script>
  <script src="/static/js/bootstrap-datepicker.js"></script>
  <script src="/static/js/jquery.timepicker.min.js"></script>
  <script src="/static/js/scrollax.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="/static/js/google-map.js"></script>
  <script src="/static/js/main.js"></script>
  <script>
	  function payment(){

	  		if (confirm("결제하시겠습니까?"+"\n내마일리지 : "+"{{user.point}}\n"+"결제금액 : " + "{{pay_products}}\n") == true) {
	  			$('#flag').val('true')
		        document.form_pay.submit();
	  		}
	  		else {
                $('#flag').val("false");
	  			return false;
	  			}
	  		}


  </script>

    
  </body>
</html>

order/templates/menu.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Coffee - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">

    <link rel="stylesheet" href="/static/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/animate.css">
    
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/static/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="/static/css/magnific-popup.css">

    <link rel="stylesheet" href="/static/css/aos.css">

    <link rel="stylesheet" href="/static/css/ionicons.min.css">

    <link rel="stylesheet" href="/static/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="/static/css/jquery.timepicker.css">

    
    <link rel="stylesheet" href="/static/css/flaticon.css">
    <link rel="stylesheet" href="/static/css/icomoon.css">
    <link rel="stylesheet" href="/static/css/style.css">
  </head>
  <body>

  {% include "navbar.html"  %}
    <!-- END nav -->

    <section class="home-slider owl-carousel">

      <div class="slider-item" style="background-image: url(/static/images/bg_1.jpg);" data-stellar-background-ratio="0.5">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center">

            <div class="col-md-7 col-sm-12 text-center ftco-animate">
            	<h1 class="mb-3 mt-5 bread">Our Menu</h1>
	            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Menu</span></p>
            </div>

          </div>
        </div>
      </div>
    </section>




     <section class="ftco-menu mb-5 pb-5">
    	<div class="container">
    		<div class="row justify-content-center mb-5">
          <div class="col-md-7 heading-section text-center ftco-animate">
          	<span class="subheading">Discover</span>
            <h2 class="mb-4">Our Products</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          </div>
        </div>
    		<div class="row d-md-flex">
	    		<div class="col-lg-12 ftco-animate p-md-5">
		    		<div class="row">
		          <div class="col-md-12 nav-link-wrap mb-5">
		            <div class="nav ftco-animate nav-pills justify-content-center" id="v-pills-tab" role="tablist" aria-orientation="vertical">
		              <a class="nav-link active" id="v-pills-1-tab" data-toggle="pill" href="#v-pills-1" role="tab" aria-controls="v-pills-1" aria-selected="true">Coffee</a>

		              <a class="nav-link" id="v-pills-2-tab" data-toggle="pill" href="#v-pills-2" role="tab" aria-controls="v-pills-2" aria-selected="false" id="Desserts">Desserts</a>

		              <a class="nav-link" id="v-pills-3-tab" data-toggle="pill" href="#v-pills-3" role="tab" aria-controls="v-pills-3" aria-selected="false">Goods</a>
		            </div>
		          </div>
		          <div class="col-md-12 d-flex align-items-center">

		            <div class="tab-content ftco-animate" id="v-pills-tabContent">

		              <div class="tab-pane fade show active" id="v-pills-1" role="tabpanel" aria-labelledby="v-pills-1-tab">
		              	<div class="row">
							{% for cof in coffee %}
		              		<div class="col-md-4 text-center">
		              			<div class="menu-wrap">
		              				<a href="{{ cof.cd }}/detail?kind=coffee" class="menu-img img mb-4" style="background-image: url(/static/images/coffee/{{ cof.cd }}.jpg);"></a>
		              				<div class="text">
		              					<h3><a href="{{ cof.cd }}/detail?kind=coffee">{{ cof.name }}</a></h3>
		              					<p>{{ cof.text }}</p>
		              					<p class="price"><span>{{ cof.price }}</span></p>
		              					<p><a href="{{ cof.cd }}/detail?kind=coffee" class="btn btn-primary btn-outline-primary">Add to cart</a></p>
		              				</div>
		              			</div>
		              		</div>
							{% endfor %}



		              	</div>
		              </div>

		              <div class="tab-pane fade" id="v-pills-2" role="tabpanel" aria-labelledby="v-pills-2-tab">
		                <div class="row">
                            {% for des in desserts %}
		              		<div class="col-md-4 text-center">
		              			<div class="menu-wrap">
		              				 <a href="{{ des.cd }}/detail?kind=desserts" class="menu-img img mb-4" style="background-image: url(/static/images/desserts/{{ des.cd }}.jpg);"></a>
		              				<div class="text">
		              					<h3><a href="{{ des.cd }}/detail?kind=desserts">{{ des.name }}</a></h3>
		              					<p>{{ des.text }}</p>
		              					<p class="price"><span>{{ des.price }}</span></p>
		              					<p><a href="{{ des.cd }}/detail?kind=desserts" class="btn btn-primary btn-outline-primary">Add to cart</a></p>
		              				</div>
		              			</div>
		              		</div>
                            {% endfor %}

		              	</div>
		              </div>

		              <div class="tab-pane fade" id="v-pills-3" role="tabpanel" aria-labelledby="v-pills-3-tab">
		                <div class="row">
                            {% for god in goods %}
		              		<div class="col-md-4 text-center">
		              			<div class="menu-wrap">
		              				<a href="{{ god.cd }}/detail?kind=goods" class="menu-img img mb-4" style="background-image: url(/static/images/goods/{{ god.cd }}.jpg);"></a>
		              				<div class="text">
		              					<h3><a href="{{ god.cd }}/detail?kind=goods">{{ god.name }}</a></h3>
		              					<p>{{ god.text }}</p>
		              					<p class="price"><span>{{ god.price }}</span></p>
		              					<p><a href="{{ god.cd }}/detail?kind=goods" class="btn btn-primary btn-outline-primary">Add to cart</a></p>
		              				</div>
		              			</div>
		              		</div>
                            {% endfor %}

		              	</div>
		              </div>
		            </div>
		          </div>
		        </div>
		      </div>
		    </div>
    	</div>
    </section>

  {% include "footer.html" %}

  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="/static/js/jquery.min.js"></script>
  <script src="/static/js/jquery-migrate-3.0.1.min.js"></script>
  <script src="/static/js/popper.min.js"></script>
  <script src="/static/js/bootstrap.min.js"></script>
  <script src="/static/js/jquery.easing.1.3.js"></script>
  <script src="/static/js/jquery.waypoints.min.js"></script>
  <script src="/static/js/jquery.stellar.min.js"></script>
  <script src="/static/js/owl.carousel.min.js"></script>
  <script src="/static/js/jquery.magnific-popup.min.js"></script>
  <script src="/static/js/aos.js"></script>
  <script src="/static/js/jquery.animateNumber.min.js"></script>
  <script src="/static/js/bootstrap-datepicker.js"></script>
  <script src="/static/js/jquery.timepicker.min.js"></script>
  <script src="/static/js/scrollax.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="/static/js/google-map.js"></script>
  <script src="/static/js/main.js"></script>
    
  </body>
</html>