accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # 로그인/로그아웃
    path('login/', views.log_in, name='login'),
    path('signup/', views.sign_up, name='signup'),
    path('logout/', views.log_out, name='logout'),
    # 고객의소리
    path('list/', views.p_list, name='list'),
    path('create_voc/', views.p_create, name='create_voc'),
    path('<int:post_id>/delete/', views.p_delete, name='delete'),
    path('<int:post_id>/update/', views.p_update, name='update'),
    path('<int:post_id>/detail/', views.p_detail, name='detail'),
    path('<int:comment_id>/<int:post_id>/c_delete/', views.c_delete, name='c_delete')
]

order/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView
from order import views

app_name = 'order'


urlpatterns = [
    #김은수
    path('menu', views.menu, name='menu'),
    path('<int:product_cd>/detail', views.detail, name='detail'),
    path('cart', views.cart, name='cart'),
    path('<int:cart_id>/delete',views.cart_delete, name='c_delete'),
    path('address', views.address, name='address'),
    path('insert_adr', views.insert_adr, name='insert_adr')

    #김은수
]

starbucks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView
from starbucks import views

urlpatterns = [

    path('accounts/', include('accounts.urls')),  # 아인
    url(r"^$",  views.give_reviews, name="home"),  # 근웅
    # url(r"^$", TemplateView.as_view(template_name="index.html"), views.give_reviews,name="home"),
    path('admin/', admin.site.urls),
    path("membership/", include("membership.urls")),
    path('order/', include('order.urls'))
]

accounts/models.py
from django.db import models


class User(models.Model):
    user_name = models.CharField('이름', max_length=10)
    user_id = models.CharField('아이디', max_length=20, unique=True)
    password = models.CharField('비밀번호', max_length=100)
    phone_num = models.CharField('전화번호', max_length=13, default=0)
    point = models.IntegerField('마일리지', default=0)
    select_adr = models.CharField(max_length=20, blank=True, null=True) #김은수

    def __str__(self):
        return self.user_id

    class Meta:
        db_table = "user"


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.TextField('글제목', max_length=1000)
    contents = models.TextField('글내용', max_length=1000)
    created_date = models.DateField('작성시간', null=True)
    qtype = models.CharField('문의유형', max_length=15, default='매장')
    hit = models.PositiveIntegerField('조회수', default=0)

    def __str__(self):
        return self.title

    @property
    def update_counter(self):
        self.hit = self.hit + 1
        self.save()


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, blank=True)
    author = models.CharField('댓글 작성자', max_length=200)
    text = models.TextField('댓글 내용', max_length=1000)
    created_date = models.DateField('작성시간', null=True)

    def __str__(self):
        return self.text

accounts/forms.py
from django import forms
from accounts.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['author', 'title', 'contents']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['author', 'text']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404

from accounts.models import User, Post, Comment
from datetime import datetime
from accounts.forms import PostForm, CommentForm
from django.http import HttpResponse, HttpResponseRedirect

from django.contrib import messages


def log_in(request):
    # post 방식
    if request.method == 'POST':
        user_id = request.POST['user_id']
        password = request.POST['password']
        if User.objects.filter(user_id=user_id).exists() == True: # user_id 가 일치하면 True
            user = get_object_or_404(User, user_id=user_id)  # 변수 선언
            if user.password == password:
                request.session['user_id'] = user_id
                request.session['check'] = 1
                request.session['user_n'] = user.id
            else:
                messages.add_message(request, messages.INFO, '가입하지 않은 아이디이거나, 잘못된 비밀번호입니다.')
                return render(request, 'login.html')

        else:
            messages.add_message(request, messages.INFO, '가입하지 않은 아이디이거나, 잘못된 비밀번호입니다.')
            return render(request, 'login.html')

        return redirect('/')
    # get 방식
    return render(request, 'login.html')


def sign_up(request):
    # signup 으로 POST 요청이 왔을 때, 새로운 유저를 만드는 절차를 밟는다.
    if request.method == 'POST':
        request.session['tmp_flag'] = -1
        user_id = request.POST['user_id']  # 변수 선언
        if User.objects.filter(user_id=user_id).exists() == False:  # user_id 중복이 되면 False
        # password와 confirm에 입력된 값이 같다면
            if request.POST['password1'] == request.POST['password2']:
                # user 객체를 새로 생성
                user = User(user_id=request.POST['user_id'], password=request.POST['password1'],
                            user_name=request.POST['user_name'], phone_num=request.POST['phone_num'])
                user.save()
                request.session['user_id'] = user_id
                request.session['check'] = 0    # 로그인 성공시 화면 넘어가기


                return redirect('accounts:login')
            else :
                request.session['tmp_flag'] = 0
                messages.add_message(request, messages.INFO, '비밀번호가 일치하지 않습니다.')
                return redirect('/accounts/signup/')
        else:
            request.session['tmp_flag'] = 1
            messages.add_message(request, messages.INFO, '이미 존재하는 아이디입니다.')
            return redirect('/accounts/signup/')
    # signup으로 GET 요청이 왔을 때, 회원가입 화면을 띄워준다.
    return render(request, 'signup.html')


def log_out(request):
    request.session['check'] = 0
    del request.session['user_id']

    return redirect('/')


# def cash(request):
#     if request.method == 'POST':
#         user = get_object_or_404(User, user_id=request.session['user_id'])
#         user.point += int(request.POST['cash'])
#         user.save()
#         return redirect('/')
#
#     return render(request, 'cash.html')


def p_list(request):
    my_list = Post.objects.all().order_by('-id')
    return render(request, 'list.html', {'list': my_list})


def p_create(request):

    if not request.session['check'] == 1:
        return HttpResponse('<script type="text/javascript">alert("로그인이필요합니다.");history.back(); '
                            '</script>')

    if request.method == 'POST':
        post = Post()
        post.author_id = request.session['user_n']
        post.title = request.POST['title']
        post.contents = request.POST['contents']
        post.qtype = request.POST['choice']
        post.created_date = datetime.now()
        post.save()
        return redirect('accounts:list')
        # return redirect('/accounts/list/')
        # post = Post(author=request.POST['author'], title=request.POST['title'], contents=request.POST['contents'])

    else:
        flag = False
        return render(request, 'create_voc.html', {"flag" : flag})


def p_delete(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()

    return redirect('accounts:list')


# def p_update(request, post_id):
#
#     post = get_object_or_404(Post, pk=post_id)
#     post
#
#     return redirect('accounts:list')

def p_update(request, post_id):

    post = Post.objects.get(id=post_id)

    if request.method == 'POST':
        post.author_id = request.session['user_n']
        post.title = request.POST['title']
        post.contents = request.POST['contents']
        post.qtype = request.POST['choice']
        post.created_date = datetime.now()
        post.save()
        return redirect('accounts:list')

    else:
        # 작성자 : 김은수

        flag = True

        comment = post.comment_set.all()
        comment.author = request.session['user_n']
        comment_form = CommentForm(request.POST)
        post_form = PostForm(instance=post)

        for i in post_form.fields:
            post_form.fields[i].disabled=True

        context = {'comment_list': comment, 'post': post, "flag": flag}

        return render(request, 'update.html',context)
    # ------------------------


    # if request.method == 'POST':
    #     post_form = PostForm(request.POST, instance=post)
    #
    #     if post_form.is_valid():
    #         post_form.save()
    #         return redirect('reviews:list')


def p_detail(request, post_id):

    post = get_object_or_404(Post, pk=post_id)

    if request.method == 'POST':

        comment = Comment()

        comment.text = request.POST['text']
        comment.post = post
        comment.created_date = datetime.now()
        comment.author = request.session['user_id']
        comment.save()

        return redirect(f'/accounts/{post_id}/detail/')

    else:
        comment = post.comment_set.all()
        comment.author = request.session['user_n']
        comment_form = CommentForm(request.POST)
        post_form = PostForm(instance=post)
        context = {'comment_list': comment, 'post_form': post_form, 'comment_form': comment_form, 'post': post}

        for i in post_form.fields:
            post_form.fields[i].disabled=True

        return render(request, 'detail.html', context)


def c_delete(request, comment_id, post_id):

    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    path = "/accounts/{}/detail".format(post_id)
    return redirect(path)


# def hits(request, no=0):
#     if no == 0: return HttpResponseRedirect('list')
#
#     post = Post.objects.filter(id=no)
#     post.update(hit=F('hit')+1)
#     data = {
#         'post':post[0]
#     }
#     return render(request, 'accounts:list', data)

accounts/templates/create_voc.html
<!DOCTYPE html>
<html lang="en">
  <head>

    <title>Coffee - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">

    <link rel="stylesheet" href="/static/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/animate.css">

    <link rel="stylesheet" href="/static/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/static/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="/static/css/magnific-popup.css">

    <link rel="stylesheet" href="/static/css/aos.css">

    <link rel="stylesheet" href="/static/css/ionicons.min.css">

    <link rel="stylesheet" href="/static/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="/static/css/jquery.timepicker.css">


    <link rel="stylesheet" href="/static/css/flaticon.css">
    <link rel="stylesheet" href="/static/css/icomoon.css">
    <link rel="stylesheet" href="/static/css/style.css">

      <style>
           body .option_color{
                        color:black !important;
                        }
      </style>
  </head>

  <body>
  	{% include "navbar.html"  %}
    <!-- END nav -->


    <section class="home-slider owl-carousel">

      <div class="slider-item" style="background-image: url(/static/images/bg_3.jpg);" data-stellar-background-ratio="0.5">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center">

            <div class="col-md-7 col-sm-12 text-center ftco-animate">
            	<h1 class="mb-3 mt-5 bread">새 글 작성</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'home' %}">Home</a></span> <span><a href="/accounts/list/">board</a></span></p>
            </div>

          </div>
        </div>
      </div>
    </section>

    <section class="ftco-section">
      <div class="container">
        <div class="row">
          <div class="col-xl-12 ftco-animate">
              {% block container %}
                <form method="post" class="billing-form ftco-bg-dark p-3 p-md-5">
                {% csrf_token %}
                <h3 class="mb-4 billing-heading">글 작성</h3>
	          	<div class="row align-items-end">

                    <!-- 닉네임 -->

                    <!-- 제목 -->
	          		<div class="col-md-12">
	                <div class="form-group">
	                	<label >제목</label>
	                  <input name="title" type="text" class="form-control" placeholder="제목을 입력하세요.">
	                </div>
	                </div>
                    <!-- 문의 유형 -->
                    <div class="w-100"></div>
		            <div class="col-md-12">
		            	<div class="form-group" name="choice2">
		            		<label >문의유형</label>
		            		<div class="select-wrap">
		                  <div class="icon"><span class="ion-ios-arrow-down"></span></div>

		                  <select name="choice" id="choice" class="form-control">
		                  	<option class="option_color" value="매장">매장</option>

		                    <option class="option_color" value="시스템">시스템</option>
		                    <option class="option_color" value="제품/상품">제품/상품</option>
		                    <option class="option_color" value="프로모션/이벤트">프로모션/이벤트</option>
		                    <option class="option_color" value="기프트카드">기프트카드</option>
		                    <option class="option_color" value="고객센터">고객센터</option>
		                  </select>
		                </div>
		            	</div>
		            </div>
		            <div class="w-100"></div>
                    <!-- 글 내용 -->
		            <div class="w-100"></div>
		            <div class="col-md-12">
		            	<div class="form-group">
	                	<label>글 내용</label>
                        <textarea name="contents" cols="100" rows="15" class="form-control" placeholder="내용을 입력하세요."></textarea>
	                    </div>
		            </div>

                    <!-- 연락처 -->
		            <div class="w-100"></div>
		            <div class="col-md-6">
	                <div class="form-group">
	                	<label>연락처</label>
	                  <input type="text" class="form-control" placeholder="ex) 010-1234-5678">
	                </div>
	                </div>
                    <!-- 연락 받으실 이메일 -->
                    <div class="col-md-6">
                    <div class="form-group">
                        <label for="emailaddress">답변 받으실 메일</label>
                      <input type="text" class="form-control" placeholder="ex) gildong@gmail.com">
                    </div>
                    </div>
                    <!-- 고객의소리 등록 버튼 -->
                    {% if flag %}
                    <button class="btn btn-primary py-3 px-5" onclick="create()">수정하기</button>
                    {% else %}
                    <button class="btn btn-primary py-3 px-5" onclick="create()">고객의 소리 등록하기</button>
                    {% endif %}

                    </div>
<!--                <div class="w-100"></div>-->
<!--                <div class="col-md-12">-->
<!--                	<div class="form-group mt-4">-->
<!--										<div class="radio">-->
<!--										  <label class="mr-3"><input type="radio" name="optradio"> Create an Account? </label>-->
<!--										  <label><input type="radio" name="optradio"> Ship to different address</label>-->
<!--										</div>-->
<!--									</div>-->
<!--                </div>-->
                 </form><!-- END -->
              {% endblock %}
          </div>
        </div>
      </div>
    </section> <!-- END of SECTION -->




  {% include "footer.html" %}


  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="/static/js/jquery.min.js"></script>
  <script src="/static/js/jquery-migrate-3.0.1.min.js"></script>
  <script src="/static/js/popper.min.js"></script>
  <script src="/static/js/bootstrap.min.js"></script>
  <script src="/static/js/jquery.easing.1.3.js"></script>
  <script src="/static/js/jquery.waypoints.min.js"></script>
  <script src="/static/js/jquery.stellar.min.js"></script>
  <script src="/static/js/owl.carousel.min.js"></script>
  <script src="/static/js/jquery.magnific-popup.min.js"></script>
  <script src="/static/js/aos.js"></script>
  <script src="/static/js/jquery.animateNumber.min.js"></script>
  <script src="/static/js/bootstrap-datepicker.js"></script>
  <script src="/static/js/jquery.timepicker.min.js"></script>
  <script src="/static/js/scrollax.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="/static/js/google-map.js"></script>
  <script src="/static/js/main.js"></script>
  <script>
      function create(){
        alert("작성완료!");
      }

  </script>

  </body>
</html>

accounts/templates/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>

    <title>Coffee - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">

    <link rel="stylesheet" href="/static/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/animate.css">

    <link rel="stylesheet" href="/static/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/static/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="/static/css/magnific-popup.css">

    <link rel="stylesheet" href="/static/css/aos.css">

    <link rel="stylesheet" href="/static/css/ionicons.min.css">

    <link rel="stylesheet" href="/static/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="/static/css/jquery.timepicker.css">


    <link rel="stylesheet" href="/static/css/flaticon.css">
    <link rel="stylesheet" href="/static/css/icomoon.css">
    <link rel="stylesheet" href="/static/css/style.css">
  </head>

  <body>
  	{% include "navbar.html"  %}
    <!-- END nav -->


    <section class="home-slider owl-carousel">
      <div class="slider-item" style="background-image: url(/static/images/bg_3.jpg);" data-stellar-background-ratio="0.5">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center">

            <div class="col-md-7 col-sm-12 text-center ftco-animate">
            	<h1 class="mb-3 mt-5 bread">상세보기</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'home' %}">Home</a></span> <span><a href="/accounts/list/">board</a></span></p>
            </div>

          </div>
        </div>
      </div>
    </section>

        <div class="container">
          {% block container %}
            <!--조회수 카운트-->
            <div>
            <input type="hidden" value="{{post.update_counter}}">
            </div>
            <section class="billing-form ftco-bg-dark p-3 p-md-5">
                <form method="post">
                    {% csrf_token %}
                <h2 class="mb-3">{{ post.title }}</h2>
                    <p>
                        <div>
                            조회수 : {{ post.hit }}　
                            작성자 : {{ post.author }}　
                            댓글수 : {{ post.comment_set.all.count }}
                        </div>
                    </p>
                <p>{{ post.contents |linebreaksbr }}</p><br><br>

                {% if request.session.user_n == post.author_id %}
                    <a href="{% url 'accounts:delete' post.id %}" class="btn btn-primary btn-outline-primary">삭제</a>
                     <a href="{% url 'accounts:update' post.id %}" class="btn btn-primary btn-outline-primary">수정</a>
                {% endif %}
                </form>
                <br>
                <hr width = "100%" color = "grey">

                <h3 class="mb-5">Leave Comments</h3>
                    {% for comment in comment_list %}
                    <ul class="comment-list">
                        <li class="comment">
                          <div class="comment">
                            <h5>{{ comment.author }}</h5>
                            <p class="text-light">{{ post.created_date|date:"Y-m-d"}}</p>
                            <p>{{comment.text}}　
                                {% if request.session.user_id == comment.author %}
                                <a class="product-remove" href="{% url 'accounts:c_delete' comment.id post.id %}"><span class="icon-close"></span></a>
                                {% endif %}
                            </p>
                          </div>
                        </li>
                    </ul>
                    {% empty %}
                        <p>No comments here yet</p>
                    {% endfor %}
                    <div class="comment-body">
                        <form method="post">
                            {% csrf_token %}
        <!--                        <input name="author" type="text" class="form-control" placeholder="{{request.session.user_id}}" disabled>-->
                            <textarea name="text" cols="90" rows="2" class="form-control" placeholder="댓글을 입력해주세요."></textarea>
                            <br><button type="submit" class="btn btn-primary">댓글 등록</button>
                        </form>
                    </div>
            </section> <!-- END of SECTION 1 -->
              {% endblock %}
        </div>
          </div>
        </div>
      </div>
    </section> <!-- END of SECTION -->




  {% include "footer.html" %}



  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="/static/js/jquery.min.js"></script>
  <script src="/static/js/jquery-migrate-3.0.1.min.js"></script>
  <script src="/static/js/popper.min.js"></script>
  <script src="/static/js/bootstrap.min.js"></script>
  <script src="/static/js/jquery.easing.1.3.js"></script>
  <script src="/static/js/jquery.waypoints.min.js"></script>
  <script src="/static/js/jquery.stellar.min.js"></script>
  <script src="/static/js/owl.carousel.min.js"></script>
  <script src="/static/js/jquery.magnific-popup.min.js"></script>
  <script src="/static/js/aos.js"></script>
  <script src="/static/js/jquery.animateNumber.min.js"></script>
  <script src="/static/js/bootstrap-datepicker.js"></script>
  <script src="/static/js/jquery.timepicker.min.js"></script>
  <script src="/static/js/scrollax.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="/static/js/google-map.js"></script>
  <script src="/static/js/main.js"></script>

  </body>
</html>

accounts/templates/list.html
<!DOCTYPE html>
<html lang="en">
  <head>

    <title>Coffee - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">

    <link rel="stylesheet" href="/static/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/animate.css">

    <link rel="stylesheet" href="/static/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/static/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="/static/css/magnific-popup.css">

    <link rel="stylesheet" href="/static/css/aos.css">

    <link rel="stylesheet" href="/static/css/ionicons.min.css">

    <link rel="stylesheet" href="/static/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="/static/css/jquery.timepicker.css">


    <link rel="stylesheet" href="/static/css/flaticon.css">
    <link rel="stylesheet" href="/static/css/icomoon.css">
    <link rel="stylesheet" href="/static/css/style.css">
  </head>

  <body>
    {% include "navbar.html"  %}
    <!-- END nav -->

    <section class="home-slider owl-carousel">

      <div class="slider-item" style="background-image: url(/static/images/bg_3.jpg);" data-stellar-background-ratio="0.5">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center">

            <div class="col-md-7 col-sm-12 text-center ftco-animate">
            	<h1 class="mb-3 mt-5 bread">Voice of Customers</h1>
	            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'accounts:create_voc' %}">문의하기</a></span>
            </div>
          </div>
        </div>
      </div>
    </section>
            <!-- start of list -->
    		<section class="ftco-section ftco-cart">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">
    				<div>
	    				<table class="table">
						    <thead class="thead-primary">
						      <tr class="text-center">
						        <th>#</th>
						        <th>문의내용</th>
						        <th>작성자</th>
                                <th>작성날짜</th>
						        <th>조회수</th>
						      </tr>
						    </thead>
						    <tbody>
                            {% if list %}
                                  {% for post in list %}
                                  <tr class="text-center">
                                    <td class="price">{{ forloop.revcounter }}</td>
                                    <td class="product-name">
                                        <a href="{% url 'accounts:detail' post.id %}">{{ post.title }}</a>
                                        <a class="price"><span class="icon-chat" href="accounts:detail"></span>({{post.comment_set.all.count}})</a>
                                    </td>
<!--                                    <td class="price">{{ request.session.user_id }}</td> &lt;!&ndash; 작성자가 로그인 할때마다 바뀜, 로그아웃하면 안보임 &ndash;&gt;-->
                                    <td class="price">{{ post.author }}</td>
                                    <td class="price">{{ post.created_date|date:"Y-m-d" }}</td>
                                    <td class="price">{{ post.hit }}</td>
                                  </tr><!-- END TR-->
                                  {% endfor %}
                            {% else %}
                                <p>There are no posts in the board</p>
                            {% endif %}
						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
			</div>
		</section>
        <!-- end of list -->

    <section>
      <div>
        <div class="row mt-5">
          <div class="col text-center">
            <div class="block-27">
              <ul>
                <li><a href="#">&lt;</a></li>
                <li class="active"><span>1</span></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&gt;</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>


  {% include "footer.html" %}



  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="/static/js/jquery.min.js"></script>
  <script src="/static/js/jquery-migrate-3.0.1.min.js"></script>
  <script src="/static/js/popper.min.js"></script>
  <script src="/static/js/bootstrap.min.js"></script>
  <script src="/static/js/jquery.easing.1.3.js"></script>
  <script src="/static/js/jquery.waypoints.min.js"></script>
  <script src="/static/js/jquery.stellar.min.js"></script>
  <script src="/static/js/owl.carousel.min.js"></script>
  <script src="/static/js/jquery.magnific-popup.min.js"></script>
  <script src="/static/js/aos.js"></script>
  <script src="/static/js/jquery.animateNumber.min.js"></script>
  <script src="/static/js/bootstrap-datepicker.js"></script>
  <script src="/static/js/jquery.timepicker.min.js"></script>
  <script src="/static/js/scrollax.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="/static/js/google-map.js"></script>
  <script src="/static/js/main.js"></script>

  </body>
</html>